/*
 * UART_Program.c
 *
 *  Created on: Jun 14, 2021
 *      Author: MarwanAbdelsalam
 */

#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "UART_Config.h"
#include "UART_Interface.h"
#include "UART_Private.h"

void UART_VoidBaudRateSelect_NonDoubleSpeedMode(void)
{
#if UART_FREQUENCY_OSC == UART_FREQUENCY_OSC_1MHZ
	#if UART_BAUDRATE == UART_BAUDRATE_2400
	UART_U8SetUBRRValue(25);
	#elif UART_BAUDRATE == UART_BAUDRATE_4800
	UART_U8SetUBRRValue(12);
	#elif UART_BAUDRATE == UART_BAUDRATE_9600
	UART_U8SetUBRRValue(6);
	#elif UART_BAUDRATE == UART_BAUDRATE_14.4k
	UART_U8SetUBRRValue(3);
	#elif UART_BAUDRATE == UART_BAUDRATE_19.2k
	UART_U8SetUBRRValue(2);
	#elif UART_BAUDRATE == UART_BAUDRATE_28.8k
	UART_U8SetUBRRValue(1);
	#elif UART_BAUDRATE == UART_BAUDRATE_38.4k
	UART_U8SetUBRRValue(1);
	#elif UART_BAUDRATE == UART_BAUDRATE_57.6k
	UART_U8SetUBRRValue(0);
	#elif UART_BAUDRATE == UART_BAUDRATE_76.8k
	#elif UART_BAUDRATE == UART_BAUDRATE_115.2k
	#elif UART_BAUDRATE == UART_BAUDRATE_230.4k
	#elif UART_BAUDRATE == UART_BAUDRATE_250k
	#elif UART_BAUDRATE == UART_BAUDRATE_0.5M
	#elif UART_BAUDRATE == UART_BAUDRATE_1M
	#endif

#elif UART_FREQUENCY_OSC == UART_FREQUENCY_OSC_2MHZ
	#if UART_BAUDRATE == UART_BAUDRATE_2400
	UART_U8SetUBRRValue(51);
	#elif UART_BAUDRATE == UART_BAUDRATE_4800
	UART_U8SetUBRRValue(25);
	#elif UART_BAUDRATE == UART_BAUDRATE_9600
	UART_U8SetUBRRValue(12);
	#elif UART_BAUDRATE == UART_BAUDRATE_14.4k
	UART_U8SetUBRRValue(8);
	#elif UART_BAUDRATE == UART_BAUDRATE_19.2k
	UART_U8SetUBRRValue(6);
	#elif UART_BAUDRATE == UART_BAUDRATE_28.8k
	UART_U8SetUBRRValue(3);
	#elif UART_BAUDRATE == UART_BAUDRATE_38.4k
	UART_U8SetUBRRValue(2);
	#elif UART_BAUDRATE == UART_BAUDRATE_57.6k
	UART_U8SetUBRRValue(1);
	#elif UART_BAUDRATE == UART_BAUDRATE_76.8k
	UART_U8SetUBRRValue(1);
	#elif UART_BAUDRATE == UART_BAUDRATE_115.2k
	UART_U8SetUBRRValue(0);
	#elif UART_BAUDRATE == UART_BAUDRATE_230.4k
	#elif UART_BAUDRATE == UART_BAUDRATE_250k
	#elif UART_BAUDRATE == UART_BAUDRATE_0.5M
	#elif UART_BAUDRATE == UART_BAUDRATE_1M
	#endif

#elif UART_FREQUENCY_OSC == UART_FREQUENCY_OSC_4MHZ
	#if UART_BAUDRATE == UART_BAUDRATE_2400
	UART_U8SetUBRRValue(103);
	#elif UART_BAUDRATE == UART_BAUDRATE_4800
	UART_U8SetUBRRValue(51);
	#elif UART_BAUDRATE == UART_BAUDRATE_9600
	UART_U8SetUBRRValue(25);
	#elif UART_BAUDRATE == UART_BAUDRATE_14.4k
	UART_U8SetUBRRValue(16);
	#elif UART_BAUDRATE == UART_BAUDRATE_19.2k
	UART_U8SetUBRRValue(12);
	#elif UART_BAUDRATE == UART_BAUDRATE_28.8k
	UART_U8SetUBRRValue(8);
	#elif UART_BAUDRATE == UART_BAUDRATE_38.4k
	UART_U8SetUBRRValue(6);
	#elif UART_BAUDRATE == UART_BAUDRATE_57.6k
	UART_U8SetUBRRValue(3);
	#elif UART_BAUDRATE == UART_BAUDRATE_76.8k
	UART_U8SetUBRRValue(2);
	#elif UART_BAUDRATE == UART_BAUDRATE_115.2k
	UART_U8SetUBRRValue(1);
	#elif UART_BAUDRATE == UART_BAUDRATE_230.4k
	UART_U8SetUBRRValue(0);
	#elif UART_BAUDRATE == UART_BAUDRATE_250k
	UART_U8SetUBRRValue(0);
	#elif UART_BAUDRATE == UART_BAUDRATE_0.5M
	#elif UART_BAUDRATE == UART_BAUDRATE_1M
	#endif

#elif UART_FREQUENCY_OSC == UART_FREQUENCY_OSC_8MHZ
	#if UART_BAUDRATE == UART_BAUDRATE_2400
	UART_U8SetUBRRValue(207);
	#elif UART_BAUDRATE == UART_BAUDRATE_4800
	UART_U8SetUBRRValue(103);
	#elif UART_BAUDRATE == UART_BAUDRATE_9600
	UART_U8SetUBRRValue(51);
	#elif UART_BAUDRATE == UART_BAUDRATE_14.4k
	UART_U8SetUBRRValue(34);
	#elif UART_BAUDRATE == UART_BAUDRATE_19.2k
	UART_U8SetUBRRValue(25);
	#elif UART_BAUDRATE == UART_BAUDRATE_28.8k
	UART_U8SetUBRRValue(16);
	#elif UART_BAUDRATE == UART_BAUDRATE_38.4k
	UART_U8SetUBRRValue(12);
	#elif UART_BAUDRATE == UART_BAUDRATE_57.6k
	UART_U8SetUBRRValue(8);
	#elif UART_BAUDRATE == UART_BAUDRATE_76.8k
	UART_U8SetUBRRValue(6);
	#elif UART_BAUDRATE == UART_BAUDRATE_115.2k
	UART_U8SetUBRRValue(3);
	#elif UART_BAUDRATE == UART_BAUDRATE_230.4k
	UART_U8SetUBRRValue(1);
	#elif UART_BAUDRATE == UART_BAUDRATE_250k
	UART_U8SetUBRRValue(1);
	#elif UART_BAUDRATE == UART_BAUDRATE_0.5M
	UART_U8SetUBRRValue(0);
	#elif UART_BAUDRATE == UART_BAUDRATE_1M
	#endif

#elif UART_FREQUENCY_OSC == UART_FREQUENCY_OSC_16MHZ
	#if UART_BAUDRATE == UART_BAUDRATE_2400
	UART_U8SetUBRRValue(416);
	#elif UART_BAUDRATE == UART_BAUDRATE_4800
	UART_U8SetUBRRValue(207);
	#elif UART_BAUDRATE == UART_BAUDRATE_9600
	UART_U8SetUBRRValue(103);
	#elif UART_BAUDRATE == UART_BAUDRATE_14.4k
	UART_U8SetUBRRValue(68);
	#elif UART_BAUDRATE == UART_BAUDRATE_19.2k
	UART_U8SetUBRRValue(51);
	#elif UART_BAUDRATE == UART_BAUDRATE_28.8k
	UART_U8SetUBRRValue(34);
	#elif UART_BAUDRATE == UART_BAUDRATE_38.4k
	UART_U8SetUBRRValue(25);
	#elif UART_BAUDRATE == UART_BAUDRATE_57.6k
	UART_U8SetUBRRValue(16);
	#elif UART_BAUDRATE == UART_BAUDRATE_76.8k
	UART_U8SetUBRRValue(12);
	#elif UART_BAUDRATE == UART_BAUDRATE_115.2k
	UART_U8SetUBRRValue(8);
	#elif UART_BAUDRATE == UART_BAUDRATE_230.4k
	UART_U8SetUBRRValue(3);
	#elif UART_BAUDRATE == UART_BAUDRATE_250k
	UART_U8SetUBRRValue(3);
	#elif UART_BAUDRATE == UART_BAUDRATE_0.5M
	UART_U8SetUBRRValue(1);
	#elif UART_BAUDRATE == UART_BAUDRATE_1M
	UART_U8SetUBRRValue(0);
	#endif
#endif
}

void UART_VoidBaudRateSelect_DoubleSpeedMode(void)
{
#if UART_FREQUENCY_OSC == UART_FREQUENCY_OSC_1MHZ
	#if UART_BAUDRATE == UART_BAUDRATE_2400
	UART_U8SetUBRRValue(51);
	#elif UART_BAUDRATE == UART_BAUDRATE_4800
	UART_U8SetUBRRValue(25);
	#elif UART_BAUDRATE == UART_BAUDRATE_9600
	UART_U8SetUBRRValue(12);
	#elif UART_BAUDRATE == UART_BAUDRATE_14.4k
	UART_U8SetUBRRValue(8);
	#elif UART_BAUDRATE == UART_BAUDRATE_19.2k
	UART_U8SetUBRRValue(6);
	#elif UART_BAUDRATE == UART_BAUDRATE_28.8k
	UART_U8SetUBRRValue(3);
	#elif UART_BAUDRATE == UART_BAUDRATE_38.4k
	UART_U8SetUBRRValue(2);
	#elif UART_BAUDRATE == UART_BAUDRATE_57.6k
	UART_U8SetUBRRValue(1);
	#elif UART_BAUDRATE == UART_BAUDRATE_76.8k
	UART_U8SetUBRRValue(1);
	#elif UART_BAUDRATE == UART_BAUDRATE_115.2k
	UART_U8SetUBRRValue(0);
	#elif UART_BAUDRATE == UART_BAUDRATE_230.4k
	#elif UART_BAUDRATE == UART_BAUDRATE_250k
	#elif UART_BAUDRATE == UART_BAUDRATE_0.5M
	#elif UART_BAUDRATE == UART_BAUDRATE_1M
	#endif

#elif UART_FREQUENCY_OSC == UART_FREQUENCY_OSC_2MHZ
	#if UART_BAUDRATE == UART_BAUDRATE_2400
	UART_U8SetUBRRValue(103);
	#elif UART_BAUDRATE == UART_BAUDRATE_4800
	UART_U8SetUBRRValue(51);
	#elif UART_BAUDRATE == UART_BAUDRATE_9600
	UART_U8SetUBRRValue(25);
	#elif UART_BAUDRATE == UART_BAUDRATE_14.4k
	UART_U8SetUBRRValue(16);
	#elif UART_BAUDRATE == UART_BAUDRATE_19.2k
	UART_U8SetUBRRValue(12);
	#elif UART_BAUDRATE == UART_BAUDRATE_28.8k
	UART_U8SetUBRRValue(8);
	#elif UART_BAUDRATE == UART_BAUDRATE_38.4k
	UART_U8SetUBRRValue(6);
	#elif UART_BAUDRATE == UART_BAUDRATE_57.6k
	UART_U8SetUBRRValue(3);
	#elif UART_BAUDRATE == UART_BAUDRATE_76.8k
	UART_U8SetUBRRValue(2);
	#elif UART_BAUDRATE == UART_BAUDRATE_115.2k
	UART_U8SetUBRRValue(1);
	#elif UART_BAUDRATE == UART_BAUDRATE_230.4k
	#elif UART_BAUDRATE == UART_BAUDRATE_250k
	UART_U8SetUBRRValue(0);
	#elif UART_BAUDRATE == UART_BAUDRATE_0.5M
	#elif UART_BAUDRATE == UART_BAUDRATE_1M
	#endif

#elif UART_FREQUENCY_OSC == UART_FREQUENCY_OSC_4MHZ
	#if UART_BAUDRATE == UART_BAUDRATE_2400
	UART_U8SetUBRRValue(207);
	#elif UART_BAUDRATE == UART_BAUDRATE_4800
	UART_U8SetUBRRValue(103);
	#elif UART_BAUDRATE == UART_BAUDRATE_9600
	UART_U8SetUBRRValue(51);
	#elif UART_BAUDRATE == UART_BAUDRATE_14.4k
	UART_U8SetUBRRValue(34);
	#elif UART_BAUDRATE == UART_BAUDRATE_19.2k
	UART_U8SetUBRRValue(25);
	#elif UART_BAUDRATE == UART_BAUDRATE_28.8k
	UART_U8SetUBRRValue(16);
	#elif UART_BAUDRATE == UART_BAUDRATE_38.4k
	UART_U8SetUBRRValue(12);
	#elif UART_BAUDRATE == UART_BAUDRATE_57.6k
	UART_U8SetUBRRValue(8);
	#elif UART_BAUDRATE == UART_BAUDRATE_76.8k
	UART_U8SetUBRRValue(6);
	#elif UART_BAUDRATE == UART_BAUDRATE_115.2k
	UART_U8SetUBRRValue(3);
	#elif UART_BAUDRATE == UART_BAUDRATE_230.4k
	UART_U8SetUBRRValue(1);
	#elif UART_BAUDRATE == UART_BAUDRATE_250k
	UART_U8SetUBRRValue(1);
	#elif UART_BAUDRATE == UART_BAUDRATE_0.5M
	UART_U8SetUBRRValue(0);
	#elif UART_BAUDRATE == UART_BAUDRATE_1M
	#endif

#elif UART_FREQUENCY_OSC == UART_FREQUENCY_OSC_8MHZ
	#if UART_BAUDRATE == UART_BAUDRATE_2400
	UART_U8SetUBRRValue(416);
	#elif UART_BAUDRATE == UART_BAUDRATE_4800
	UART_U8SetUBRRValue(207);
	#elif UART_BAUDRATE == UART_BAUDRATE_9600
	UART_U8SetUBRRValue(103);
	#elif UART_BAUDRATE == UART_BAUDRATE_14.4k
	UART_U8SetUBRRValue(68);
	#elif UART_BAUDRATE == UART_BAUDRATE_19.2k
	UART_U8SetUBRRValue(51);
	#elif UART_BAUDRATE == UART_BAUDRATE_28.8k
	UART_U8SetUBRRValue(34);
	#elif UART_BAUDRATE == UART_BAUDRATE_38.4k
	UART_U8SetUBRRValue(25);
	#elif UART_BAUDRATE == UART_BAUDRATE_57.6k
	UART_U8SetUBRRValue(16);
	#elif UART_BAUDRATE == UART_BAUDRATE_76.8k
	UART_U8SetUBRRValue(12);
	#elif UART_BAUDRATE == UART_BAUDRATE_115.2k
	UART_U8SetUBRRValue(8);
	#elif UART_BAUDRATE == UART_BAUDRATE_230.4k
	UART_U8SetUBRRValue(3);
	#elif UART_BAUDRATE == UART_BAUDRATE_250k
	UART_U8SetUBRRValue(3);
	#elif UART_BAUDRATE == UART_BAUDRATE_0.5M
	UART_U8SetUBRRValue(1);
	#elif UART_BAUDRATE == UART_BAUDRATE_1M
	UART_U8SetUBRRValue(0);
	#endif

#elif UART_FREQUENCY_OSC == UART_FREQUENCY_OSC_16MHZ
	#if UART_BAUDRATE == UART_BAUDRATE_2400
	UART_U8SetUBRRValue(832);
	#elif UART_BAUDRATE == UART_BAUDRATE_4800
	UART_U8SetUBRRValue(416);
	#elif UART_BAUDRATE == UART_BAUDRATE_9600
	UART_U8SetUBRRValue(207);
	#elif UART_BAUDRATE == UART_BAUDRATE_14.4k
	UART_U8SetUBRRValue(138);
	#elif UART_BAUDRATE == UART_BAUDRATE_19.2k
	UART_U8SetUBRRValue(103);
	#elif UART_BAUDRATE == UART_BAUDRATE_28.8k
	UART_U8SetUBRRValue(68);
	#elif UART_BAUDRATE == UART_BAUDRATE_38.4k
	UART_U8SetUBRRValue(51);
	#elif UART_BAUDRATE == UART_BAUDRATE_57.6k
	UART_U8SetUBRRValue(34);
	#elif UART_BAUDRATE == UART_BAUDRATE_76.8k
	UART_U8SetUBRRValue(25);
	#elif UART_BAUDRATE == UART_BAUDRATE_115.2k
	UART_U8SetUBRRValue(16);
	#elif UART_BAUDRATE == UART_BAUDRATE_230.4k
	UART_U8SetUBRRValue(8);
	#elif UART_BAUDRATE == UART_BAUDRATE_250k
	UART_U8SetUBRRValue(7);
	#elif UART_BAUDRATE == UART_BAUDRATE_0.5M
	UART_U8SetUBRRValue(3);
	#elif UART_BAUDRATE == UART_BAUDRATE_1M
	UART_U8SetUBRRValue(1);
	#endif
#endif
}


void UART_VoidInitConfig(void)
{
	//variable UCSRC_COPY to modify on it then put the whole value in the UCSRC in one time
	u8 UCSRC_COPY=0b10000000;
	//U2X: Double the USART Transmission Speed Enable/Disable select (in the Asynchronous mode only)
	#if 	UART_U2X_Select == UART_U2X_DISABLE
	ClearBit(UCSRA,U2X);
	UART_VoidBaudRateSelect_NonDoubleSpeedMode();
	#elif	UART_U2X_Select == UART_U2X_ENABLE
	SetBit(UCSRA,U2X);
	UART_VoidBaudRateSelect_DoubleSpeedMode();
	#endif
	//Multi-processor Communication Mode Enable/Disable select
	#if 	UART_MULTIPROCESSOR_COMM_MODE_SELECT == UART_MULTIPROCESSOR_COMM_MODE_DISABLE
	ClearBit(UCSRA,MPCM);
	#elif	UART_MULTIPROCESSOR_COMM_MODE_SELECT == UART_MULTIPROCESSOR_COMM_MODE_ENABLE
	SetBit(UCSRA,MPCM);
	#endif
	//Receiving Complete Interrupt Enable/Disable Select
	#if 	UART_RX_COMPLETE_INTERRUPT_SELECT == UART_RX_COMPLETE_INTERRUPT_DISABLE
	ClearBit(UCSRB,RXCIE);
	#elif	UART_RX_COMPLETE_INTERRUPT_SELECT == UART_RX_COMPLETE_INTERRUPT_ENABLE
	SetBit(UCSRB,RXCIE);
	#endif
	//Transmitting Complete Interrupt Enable/Disable Select
	#if 	UART_TX_COMPLETE_INTERRUPT_SELECT == UART_TX_COMPLETE_INTERRUPT_DISABLE
	ClearBit(UCSRB,TXCIE);
	#elif	UART_TX_COMPLETE_INTERRUPT_SELECT == UART_TX_COMPLETE_INTERRUPT_ENABLE
	SetBit(UCSRB,TXCIE);
	#endif
	//Data Register(UDR) Empty Interrupt Enable/Disable Select
	#if 	UART_UDR_EMPTY_INTERRUPT_SELECT == UART_UDR_EMPTY_INTERRUPT_DISABLE
	ClearBit(UCSRB,UDRIE);
	#elif	UART_UDR_EMPTY_INTERRUPT_SELECT == UART_UDR_EMPTY_INTERRUPT_ENABLE
	SetBit(UCSRB,UDRIE);
	#endif
	//Receiver Enable/Disable Select
	#if 	UART_RECEIVER_SELECT == UART_RECEIVER_DISABLE
	ClearBit(UCSRB,RXEN);
	#elif	UART_RECEIVER_SELECT == UART_RECEIVER_ENABLE
	SetBit(UCSRB,RXEN);
	#endif
	//Transmitter Enable/Disable Select
	#if 	UART_TRANSMITTER_SELECT == UART_TRANSMITTER_DISABLE
	ClearBit(UCSRB,TXEN);
	#elif	UART_TRANSMITTER_SELECT == UART_TRANSMITTER_ENABLE
	SetBit(UCSRB,TXEN);
	#endif
	//Data Size Select 5/6/7/8/9 bits
	#if		UART_CHAR_SIZE ==	UART_CHAR_SIZE_5BITS
	ClearBit(UCSRB,UCSZ2);
	ClearBit(UCSRC_COPY,UCSZ1);
	ClearBit(UCSRC_COPY,UCSZ0);
	#elif	UART_CHAR_SIZE ==	UART_CHAR_SIZE_6BITS
	ClearBit(UCSRB,UCSZ2);
	ClearBit(UCSRC_COPY,UCSZ1);
	SetBit(UCSRC_COPY,UCSZ0);
	#elif	UART_CHAR_SIZE ==	UART_CHAR_SIZE_7BITS
	ClearBit(UCSRB,UCSZ2);
	SetBit(UCSRC_COPY,UCSZ1);
	ClearBit(UCSRC_COPY,UCSZ0);
	#elif 	UART_CHAR_SIZE ==	UART_CHAR_SIZE_8BITS
	ClearBit(UCSRB,UCSZ2);
	SetBit(UCSRC_COPY,UCSZ1);
	SetBit(UCSRC_COPY,UCSZ0);
	#elif 	UART_CHAR_SIZE ==	UART_CHAR_SIZE_9BITS
	SetBit(UCSRB,UCSZ2);
	SetBit(UCSRC_COPY,UCSZ1);
	SetBit(UCSRC_COPY,UCSZ0);
	#endif
	//UART Mode Select Synchronous/Asynchronous
	#if	UART_MODE	== UART_MODE_ASYNCHRONOUS
	ClearBit(UCSRC_COPY,UMSEL);
	#elif	UART_MODE	== UART_MODE_SYNCHRONOUS
	SetBit(UCSRC_COPY,UMSEL);
	#endif
	//UART Parity Mode Select Disabled/Even/Odd
	#if	UART_PARITY_MODE	== UART_PARITY_MODE_DISABLE
	ClearBit(UCSRC_COPY,UPM1);
	ClearBit(UCSRC_COPY,UPM0);
	#elif	UART_PARITY_MODE	== UART_PARITY_MODE_EVEN
	SetBit(UCSRC_COPY,UPM1);
	ClearBit(UCSRC_COPY,UPM0);
	#elif	UART_PARITY_MODE	== UART_PARITY_MODE_ODD
	SetBit(UCSRC_COPY,UPM1);
	SetBit(UCSRC_COPY,UPM0);
	#endif
	//UART Stop Bit Mode Select 1bit/2bits
	#if	UART_STOPBIT_MODE	== UART_STOPBIT_MODE_1BIT
	ClearBit(UCSRC_COPY,USBS);
	#elif	UART_STOPBIT_MODE	== UART_STOPBIT_MODE_2BIT
	SetBit(UCSRC_COPY,USBS);
	#endif
	//UART Clock Polarity(this bit has only benefits in synchronous mode)
	#if UART_CLOCK_POLARITY == UART_CLOCK_POLARITY_DISABLE
	ClearBit(UCSRC_COPY,UCPOL);
	#elif UART_CLOCK_POLARITY == UART_CLOCK_POLARITY_RISING_TX_FALLING_RX
	ClearBit(UCSRC_COPY,UCPOL);
	#elif UART_CLOCK_POLARITY == UART_CLOCK_POLARITY_FALLING_TX_RISING_RX
	SetBit(UCSRC_COPY,UCPOL);
	#endif


	UCSRC=UCSRC_COPY;
}

void UART_U8SetUBRRValue(u16 Copy_U16UBRRValue)
{
	if (Copy_U16UBRRValue <= 0x00FF )
		UBRRL=Copy_U16UBRRValue;
	else if ( (Copy_U16UBRRValue > 0x00FF) && (Copy_U16UBRRValue <= 0x0FFF) )
	{
		UBRRL=(u8)Copy_U16UBRRValue;
		UBRRH=((Copy_U16UBRRValue>>8));
	}
}

void UART_VoidInit(void)
{
	//Transmitter Enable
	SetBit(UCSRB,TXEN);
	//Receiver Enable
	SetBit(UCSRB,RXEN);

	//Asynchronous/synch		(UCSRC)bit6						Asynchronous=0
	//parity 					(UCSRC)bit5:4					no parity 	= 00
	//Stop bit select			(UCSRC)bit3						1 bit 		= 0
	//Character Size			(UCSRB)bit2+(UCSRC)bit2:1		8bits		= 011
	ClearBit(UCSRB,UCSZ2);
	UCSRC=0b10000110;
	// 9600 BR
	UBRRL=51;


}


void UART_VoidTransmitData(u8 Copy_U8Data)
{
	//if the UDR is not empty stuck in this while loop
	while(GetBit(UCSRA,UDRE)==0);
	//the UDR is now ready to hold new data
	UDR=Copy_U8Data;
	//hold here until the transmission is complete
	//while(GetBit(UCSRA,TXC)==0);
	// _delay_ms(100);
}


u8 UART_U8ReceiveData(void)
{
	u8 value;
	//stuck here while there's still no data to be read in the UDR
	while (GetBit(UCSRA,RXC)==0);
	value=UDR;
	return value;
}
